### ISSUE TITLE
add self and avatar link to the generated Json

### ISSUE THREAD

**Issue by ulfa** [innoq/statuses#164]
The actual Json doesn't contain the self link and the avatar link. 

 {
      "author" : "timo",
      "time" : "2015-03-13T23:47:07.205+01:00",
      "id" : 2975,
      "can-delete?" : false,
      "text" : "Alter Trick für Maven (2010): Lokale in-project repositories wenn man doch mal ein Artefakt einchecken muss: http://bit.ly/1MzgWmr"
    },

Please,  insert avatar link and a self link like the following.

"avatar" : "URI"
"self" : "URI"

**Comment by aheusingfeld** [comment]
This is related to #144. Actually you're missing more than just the two links mentioned above as you don't have

- a link to the "submit" url (including the "method")
- a link to the "reply" url (including the "method")
- a link to the "delete" url (including the "method")
- a link to the "next reply" url
- a link to the "previous reply" url
- links for pagination (see #144)

**Comment by stilkov** [comment]
Or you could just use the HTML.

**Comment by aheusingfeld** [comment]
:+1: or the atom feed but that doesn't contain all the links either
